### ISSUE TITLE
Второй этап обработки данных, создание итогового вектора фрагментов

### ISSUE THREAD

**Issue by Sergey-Shulnyaev** [Sergey-Shulnyaev/ZamZam#6]
Идея в том, чтобы реализовать класс, который возвращает по сэмплу зашумлённый сэмпл с выбранным шумом.
Объект назовём MusicEffectGen.
Следующая структура:
1. MusicEffectGen
     2.1. Различные функции, накладывающие звуковые эффекты
     2.2. Функция суммирующая все остальные. 
          2.2.1. Получает в аргумент тип шума.
          2.2.2. Возвращает функцию из 2.1. с нужным шумом.
          2.2.3. Название : функция хранятся в специальном словаре.

- [x] 1. Собрать набор различных эффектов для обработки фрагментов музыки.
- [x]     1.1. Зацикливаемые фрагменты звуков по типу: шум толпы; звонкие, глухие удары; фейерверк; шум механизмов, машин; сигналы поездов и тп; скрип и тд.
- [x]     1.2. Обработка музыки непосредственно: затихание, непостоянная громкость(громкость по синусоиде), просто тихая и т.п. 
- [x] 2. В DataGen cформировать вектор из обработанных музыкальных фрагментов.

**Comment by arti-shok** [comment]
simple di
mple
